### ISSUE TITLE
x64-bit version fails to run

### ISSUE THREAD

**Issue by mxdanger** [LewisTehMinerz/RFU#1]
I'm able to run the 32-bit version with no problem but I can't get the 64-bit version to run.

Error message:
![image](https://user-images.githubusercontent.com/32040254/77017240-27cbb200-6937-11ea-9dd8-3a3df502ed6b.png)

**Comment by LewisTehMinerz** [comment]
Interesting. Can you try and install this version of Visual C++ and run RFU again?

https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by mxdanger** [comment]
It appears that I already have that installed. 
![image](https://user-images.githubusercontent.com/32040254/77200055-130e2c00-6aa7-11ea-9502-7776e2fb5684.png)

**Comment by LewisTehMinerz** [comment]
I appear to have found the problem.

[VCRUNTIME140_1.DLL seems to only come with the Visual Studio versions of the redistributables.](https://developercommunity.visualstudio.com/content/problem/852548/vcruntime140-1dll-is-missing.html) I will try and use the solution provided (disabling FH4) and make a test build for you to try.

**Comment by LewisTehMinerz** [comment]
@mxdanger Can you try the following build and see if you still get the same problem?
[RFU-x64-dbg.zip](https://github.com/LewisTehMinerz/RFU/files/4361650/RFU-x64-dbg.zip)

**Comment by mxdanger** [comment]
@LewisTehMinerz It works now.

**Comment by Jameswilson1934** [comment]
Cannot execute "C:\Users\WINDOW~1\AppData\Local\Temp\Rar$EXa0.526\RFU.exe"

**Comment by mxdanger** [comment]
Please remove your comment, my issue has been resolved. If you have any issues create a new one.
