### ISSUE TITLE
it show me a error that un-able to connect to task sceduelder

### ISSUE THREAD

**Issue by kitty165** [LewisTehMinerz/RFU#10]
sorry im im indonesia i can't speak english but can you patch this or something?

**Comment by LewisTehMinerz** [comment]
Are you using the Windows 10 version of Roblox? I'm aware of an issue with that at the moment, I'm yet to fix it.

**Comment by christopher317** [comment]
im having a similar issue on windows 11 but its saying variable scan failed.

**Comment by LewisTehMinerz** [comment]
This should've been fixed in latest version. Make a new issue with proper information if it occurs again.
