### ISSUE TITLE
Error when using RFU on Roblox Studio

### ISSUE THREAD

**Issue by dumbdo0096** [LewisTehMinerz/RFU#11]
Basically when I run the unlocker (RFU 5.4.0), it fails to unlock Studio (but unlocks the normal Roblox Player)

Steps to reproduce the behaviour:
1- Run the RFU
2- Open Roblox Studio and wait.

You should see the following error and the frame rate will remain locked.
![image](https://user-images.githubusercontent.com/96336896/146638744-64663778-fa3e-445b-aeda-7416251439ec.png)

**Comment by LewisTehMinerz** [comment]
should be fixed as of https://github.com/LewisTehMinerz/RFU/releases/tag/5.4.1
