### ISSUE TITLE
fps unblocker not working when tabed in

### ISSUE THREAD

**Issue by christopher317** [LewisTehMinerz/RFU#12]
**Describe the bug**
when tabed into roblox the fps is still caped at 60, when i tab out of the game the frame rate goes up as if the fps unblocker is working

**To Reproduce**
1. start the fps unblocker on windows 11
2. go into any game and tab in

**Expected behavior**
the framerate is caped at 60

**Desktop (please complete the following information):**
 - Version 5.4.1

**Additional context**
i am on windows 11 and the latest virson of roblox

**Comment by christopher317** [comment]
![image](https://user-images.githubusercontent.com/86526198/149972936-ee406fc3-2b69-40be-9765-8fc94d760e48.png)
it also throws a error in the console when i start it and im tabed in

**Comment by christopher317** [comment]
tabed out
![image](https://user-images.githubusercontent.com/86526198/149973334-3d301d3b-01b1-4d0e-9c16-57f0bb741e9f.png)
tabed in
![image](https://user-images.githubusercontent.com/86526198/149973358-1a1ca521-ecd3-4bbc-a72d-eb62a6957786.png)

**Comment by LewisTehMinerz** [comment]
This is most likely related to Radeon or Nvidia drivers, or some other third party software that enforces v-sync, especially if your monitor is 60Hz.
