### ISSUE TITLE
V-sync

### ISSUE THREAD

**Issue by AwakeningLol** [LewisTehMinerz/RFU#14]
Hi. It would be great if RFU could disable vsync in roblox, because even with high the high frames that you can get with this program, you still lag a lot. If you could do that it would be awesome

**Comment by AwakeningLol** [comment]
Vsync introduces a lot of input lag by capping the amount of frames your
gpu renders. It caps your frames at your monitors refresh rate (in my case
60hz). With the roblox fps unlocker its really glitchy. It uncaps your
frames but it doesnt disable vsync. And normally its not possible to get
higher frames than your monitors refresh rate without disabling vsync. I
think that this issue might be exclusively on 60hz monitors.

**Comment by LewisTehMinerz** [comment]
That's not related to the unlocker. That'll be related to some other software you have on your PC like Radeon or Nvidia drivers. I'm able to run at over my monitor's refresh rate (which is 144Hz, I can however over that easily) so you must have some sort of other software or driver that's limiting the game to the refresh rate.

**Comment by AwakeningLol** [comment]
Its actually an issue with roblox. Ive tried turning off vsync on both
nvidia and amd drivers on different pcs. I actually wanted to submit a
suggestion on github because i thought that there might be a way to work
around roblox's forced vsync

Lewis Crichton ***@***.***> schrieb am Mo., 14. März 2022,
21:01:

**Comment by LewisTehMinerz** [comment]
Unfortunately I can't replicate the issue myself.
![](https://discord.coffee/jqJxphL.png)
In both windowed and fullscreen modes there is no v-sync.
