### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by muilas** [LewisTehMinerz/RFU#16]
I downloaded all the files that I need to, ran the fps unlocker as administrator but it still doesn't work. It just tells me to run it as administrator.

![image](https://user-images.githubusercontent.com/107473871/173555920-0cba3dd8-c692-486a-93db-f5e0f91c5903.png)

**Comment by LewisTehMinerz** [comment]
Well, that error indicates you don't have permission:
```
ERROR_ACCESS_DENIED
5 (0x5)
Access is denied.
```
Which is weird if you're running it under administrator. I also can't replicate it here.

**Comment by muilas** [comment]
I do have 2 profiles, but both of them have administrator rights.

**Comment by muilas** [comment]
so I tried it with my original windows profile and it works for some reason

**Comment by LewisTehMinerz** [comment]
That sounds like you were running Roblox and RFU on separate user profiles unintentionally, which won't work as far as I'm aware.

**Comment by muilas** [comment]
So the only way to fix it, is installing roblox on the profile that i want to use, right?

**Comment by LewisTehMinerz** [comment]
That would be correct, yes. I'm not sure how you're running Roblox across multiple user profiles since it's a per-user install.
