### ISSUE TITLE
it wont work on mine bruh

### ISSUE THREAD

**Issue by kennethxc33** [LewisTehMinerz/RFU#18]
is said The code execution cannot procceed becuase MSVP140.dll was not found. Reinstallinng the program may fix the problem.
also it said the samething TWICE :/

**Comment by kennethxc33** [comment]
pls show me how

**Comment by LewisTehMinerz** [comment]
https://github.com/LewisTehMinerz/RFU#im-getting-an-error-saying-that-vcruntime140dll-is-missing-why
