### ISSUE TITLE
Performance tests between original and fork

### ISSUE THREAD

**Issue by LewisTehMinerz** [LewisTehMinerz/RFU#2]
In my own testing, I found that my version of the tool actually got ~33% more frames than the original (120 FPS vs 180 FPS) which I call black magic. However, to prevent bias, I'd like some independent tests from people.

If you can, please try and run both the latest versions of the original Roblox FPS Unlocker and my version with the same settings (FPS cap set to none) and post your screenshots here. Use SHIFT+F4 to get your FPS. Note that you cannot run both at the same time as I and axstin prevent it, and even if I didn't they would conflict.

Thank you in advance. ❤️

**Comment by Vili1** [comment]
- **original tool** the fps is between 120 and 140 at best 
![image](https://user-images.githubusercontent.com/42891941/79549797-1e517900-80a0-11ea-821f-9d60360a5469.png)
- cpu usage from 0.00% to 0.08% the memory usage is 2.4 mb without the console the console adds 6.4 to 6.3 mb 
![image](https://user-images.githubusercontent.com/42891941/79550097-9324b300-80a0-11ea-8e7f-ab71f2d6790f.png)
- size of the executable file 
![image](https://user-images.githubusercontent.com/42891941/79550789-7fc61780-80a1-11ea-8374-86610a6c70ff.png)

- **your tool** the fps is between 120 and 140 at best 
![image](https://user-images.githubusercontent.com/42891941/79548967-f281c380-809e-11ea-87f7-b74c617f0ae1.png)
- cpu usage from 0.00% to 0.05% the memory usage is 2.4 mb without the console the console adds 6.4 to 6.3 mb 
![image](https://user-images.githubusercontent.com/42891941/79549076-22c96200-809f-11ea-8d26-974893ddba58.png)
- size of the executable file 
![image](https://user-images.githubusercontent.com/42891941/79550677-5c02d180-80a1-11ea-866e-c288e83f71ba.png)

- **my own tool** the fps is between 120 and 140 at best 
![image](https://user-images.githubusercontent.com/42891941/79551025-cd428480-80a1-11ea-8d36-7d46b03d29ed.png)
- cpu usage from 0.00% to 0.02% the memory usage is 0.5 mb without the console the console adds 6.4 to 6.3 mb 
![image](https://user-images.githubusercontent.com/42891941/79551438-55c12500-80a2-11ea-83af-922e4cfe49d8.png)
- size of the executable file 
![image](https://user-images.githubusercontent.com/42891941/79551550-7b4e2e80-80a2-11ea-8ef6-ba8ce5194abe.png)
- note that my own tool doesn't use AOB scans its simply uses a pointer also it doesn't have any other features for example support for Roblox studio and the windows 10 version of Roblox from the Microsoft store

**Comment by Vili1** [comment]
- it shouldn't really have a difference between the fps in each of the tools its simply changing a value in memory 
- the only difference is in cpu/memory usage and executable size 
- for optimization u can try closing opened handel's

**Comment by Vili1** [comment]
also lets be hones no one is going to use our tools anyway xD

**Comment by LewisTehMinerz** [comment]
Shrug, I mainly did this fork to help me learn C++ more and it has helped me learn a lot. I wonder why the original gave me less FPS -- maybe the CPU usage from it gave Roblox a slight performance hit and since my version has a lesser average CPU, whilst minimal, it might have affected my testing in that regard.

**Comment by Vili1** [comment]
> I wonder why the original gave me less FPS -- maybe the CPU usage from it gave Roblox a slight performance hit and since my version has a lesser average CPU, whilst minimal, it might have affected my testing in that regard.

Tbh i have no idea but if i have to guess maybe there was something running in the background that was using 3D hardware acceleration , maybe like discord or youtube idk .

**Comment by LewisTehMinerz** [comment]
I tried multiple times and got consistent results, maybe it's just a bug with the original on my machine or something? ¯\\\_(ツ)\_/¯

**Comment by Vili1** [comment]
yeh probably i dont get the Roblox devs tho like this should be a in game feature if u ask me bcs those tools are just changing a value in memory im sure that thing can be easily added in the game but still

**Comment by LewisTehMinerz** [comment]
Closing, guess it was just placebo.
