### ISSUE TITLE
task scheduler issue

### ISSUE THREAD

**Issue by aimholic** [LewisTehMinerz/RFU#21]
Don't really know if this is just me but I ran RFU and it stated that it couldn't find the 'TaskScheduler' due to a Roblox update. I restarted my computer and tried to open it manually but the result is the same. The FPS unlocker itself worked perfectly fine yesterday and I don't recall myself updating Roblox unless it did it automatically. 

**To Reproduce**
1. Run RFU 5.4.3 x64 on start-up or manually.

**Expected behavior**
The RFU icon should be displaying on the bottom right side of the screen and the capped FPS of Roblox should have been unlocked like normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/117881208/200988764-23d54ef3-4e9a-41f3-9b71-1b50e7fc10d4.png)
![image](https://user-images.githubusercontent.com/117881208/200988853-1b4b3b95-3d8a-43dd-bf42-d5bf63514f77.png)
![image](https://user-images.githubusercontent.com/117881208/200989156-6f4c3d78-a4f7-4bb8-98d0-422e69d588ad.png)
^ taken in arsenal with RFU not working (I typically run around 144fps on a 143hz monitor)

**Desktop (please complete the following information):**
 - Version 5.4.3

**Comment by LewisTehMinerz** [comment]
There was a Roblox update on Wednesday. Will have a fix once I'm home.
