### ISSUE TITLE
Regarding 32-bit/x86

### ISSUE THREAD

**Issue by LewisTehMinerz** [LewisTehMinerz/RFU#4]
Distinctions:
RFU refers to **this** software and Roblox FPS Unlocker refers to the original.

RFU currently provides a 32-bit build of the software. Roblox FPS Unlocker has stopped doing so since 4.4.0. 32-bit builds of both have historically been the least used (at the time of writing, 2.1k and 600 downloads of 64-bit and 32-bit, respectively, on RFU). Not only is it a lesser used version, it is more prone to being detected by antiviruses for no discernable reason. 64-bit is fine, 32-bit is not.

I'm tempted to go the route of Roblox FPS Unlocker and stop providing 32-bit builds since they have caused confusion and it is highly likely that a lot of its downloads are people not understanding what the difference is. Most PCs are 64-bit nowadays anyway and I haven't come across a 32-bit PC for a long time.

If you have a 32-bit PC, please let me know. Even if it is just for one person, I will continue providing 32-bit builds.

**Comment by MrZultra** [comment]
Same Here.

**Comment by BlueSoSad** [comment]
i have 32 bit pc

**Comment by ImNoobFake** [comment]
I have 32 bit Laptop

**Comment by LewisTehMinerz** [comment]
I will keep providing 32-bit builds.
