### ISSUE TITLE
If this is a fork of axstin's FPS Unlocker, then why is it not marked as such in Github?

### ISSUE THREAD

**Issue by Derpitron** [LewisTehMinerz/RFU#5]
Why create a whole new repository when you could just fork it via github? it would allow for us to compare changes and commits between this repo and upstream

**Comment by LewisTehMinerz** [comment]
it was hardforked on purpose; due to my code cleanup sweeps it basically becomes unmergeable with the original upstream so i merge new changes in by hand, then run cleanup.

**Comment by Derpitron** [comment]
Ok, thank you for the clarification 👍
