### ISSUE TITLE
RFU + rbxfpsunlocker refusing to work when tabbed onto roblox

### ISSUE THREAD

**Issue by kreggle** [LewisTehMinerz/RFU#9]
**Describe the bug**

My FPS locks to 59 regardless of my graphical setting on any game I play when I'm tabbed into roblox, as soon as I tab out of roblox my fps dramatically increases as expected

**To Reproduce**

1) Tab into roblox
2) Press shift+f5
3) Look at the change in fps while you tab in and out of roblox

**Expected behavior**
I should get above 140fps on 1-10 graphics either in windowed or fullscreen mode

**Desktop (please complete the following information):**

 - Version 5.4

**Additional context**

 This happens in windows or fullscreen and I have absolutely no idea why

https://user-images.githubusercontent.com/91433160/134821351-ad62fb7b-b68b-48ba-9f5d-dc294be3019b.mp4

**Comment by LewisTehMinerz** [comment]
Just so I know it isn't my game being faulty, can you do that test again with SHIFT+F5?

**Comment by kreggle** [comment]
Of course!



https://user-images.githubusercontent.com/91433160/134825085-2c524734-8674-489f-a674-83b03e6359c9.mp4

**Comment by kreggle** [comment]
This happens with the original FPS unlocker

It's been bothering me for days, I've practically tried everything to get it to work and it never did

I even went as far as reinstalling windows and on a new drive, reinstalled roblox too and same problem

**Comment by LewisTehMinerz** [comment]
Since this affects both, and you have an Nvidia card, I'm going to place my bets that this is an issue with Nvidia forcing VSync on games rather than the FPS unlocker. Can you attempt to turn off VSync in the control panel and report back?

1. Go to the Nvidia Control Panel
2. Go to 3D Settings
3. Make sure VSync is off globally and for Roblox.

**Comment by kreggle** [comment]
![image](https://user-images.githubusercontent.com/91433160/134968803-93301e6a-47cd-4ec5-9a82-ad21ccc906b9.png)

It's been off, when I reinstalled windows I made sure to turn it off, I may just need to reset to default settings however

**Comment by kreggle** [comment]
I'm not sure what the issue really is, I've made sure that my refresh rate is the correct refresh rate too, how strange this is

**Comment by LewisTehMinerz** [comment]
Neither, but if it happens with the original FPS unlocker too there's something running on your machine that forcefully locks the framerate of Roblox. The FPS unlocker is doing its job (evident by the fact that when Roblox isn't focused it spikes up to uncapped FPS). I'm not too sure how to help, sorry.
